modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Team-Core/issues"
displayURL="https://u-team.info/mods/uteamcore"
#logoFile="logo.png" #We cant use the logo, cause the image will not be rescaled
credits="Team U-Team"
authors="HyCraftHD, MrTroble"

[[mods]]
	modId="uteamcore"
	version="${file.jarVersion}"
	displayName="U Team Core"
	updateJSONURL="https://api.u-team.info/update/uteamcore.json"
	description="This libary contains many useful modding stuff!"
	
	[[dependencies.uteamcore]]
	    modId="forge"
	    mandatory=true
	    versionRange="[25,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.uteamcore]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.13.2]"
	    ordering="NONE"
	    side="BOTH"
    
    
[[mods]]
	modId="uteamtest"
	version="1.0.0"
	displayName="U Team Test"
	description="This is just a test mod to test uteamcore"
	
	[[dependencies.uteamtest]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="${file.jarVersion}"
	    ordering="NONE"
	    side="BOTH"